### PR TITLE
Fix directory separation problems on Windows machine

### LINKED ISSUE #4: Incorrect directory separators under windows.
This is a great package, but had to make a few small tweaks to get it working under my windows machine.

There were 2 places in the code that are checking a regex against a filepath, however on windows my filepaths have backslashes instead of forward slashes causing the regex to fail to match.

For example in `PathResolver.php` getRealPath returns on my machine:
`C:\path\to\www\app\vendor\package\file.php`
instead of the expected
`C:/path/to/www/app/vendor/package/file.php`

to workaround this issue I simply changed any calls to `$fileInfo->getRealPath()` to `str_replace('\\', '/', $fileInfo->getRealPath())` in the following files:
* PathResolver.php
* PatchDiffer.php

I can submit a pull request with this fix if you'd like?

### LINKED ISSUE #10: Issues with patching on Local Windows Machine
I had a couple of issues while applying a patch on my local windows . I'll mention them here if someone else faces the same issues. If there is a better way please let me know. 

- The directory separator for windows (#4) needed to be changed using PR #9 
- The composer-patches requires the package to either be a git package or the fall back method of using `patch` command. 
    `patch` command is linux based. There are two ways to solve this. 
     1. Install the package via its git source using `compose require [package] --prefer-source`. 
         This will get the package from git rather than the dist version. 
     2. Install Patch for windows from [here.](https://gnuwin32.sourceforge.net/packages/patch.htm) and add it to your path. Note: I could not get this to work on my machine, as running patch opened a new command line but nothing happened after that. 
- I had to run composer-install to install other packages, then run `compose require [package] --prefer-source` just for that specific package, so that composer-patches will recognise it as a git package, and apply patch, or add repo directly to composer.   
- The .patch file generated `--- /dev/null`, which gave me `error: new file dist/client.js depends on old contents`. 
```
   --- /dev/null
   +++ ../dist/client.js
```
So, I updated the patched file to
```
--- ../dist/client.js
+++ ../dist/client.js
```
   based on the answer [here](https://stackoverflow.com/a/52221725/4714773) which fixed the issue for me.

### PR DESCRIPTION
**Pull request by BoGnY**
Fork and rebase of #9 for fix #4 and fix #10

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks 👍

Could you extract this to a method, so we can re-use it have it clearly seprated? Something like "normalizePath"

**Comment by BoGnY** [comment]
[**@TomasVotruba**](https://github.com/TomasVotruba) commented on [Sep 27, 2023, 1:03 PM GMT+2](https://github.com/symplify/vendor-patches/pull/14#issuecomment-1737177866 "2023-09-27T11:03:08Z - Replied by Github Reply Comments"):
> Thanks 👍
> 
> Could you extract this to a method, so we can re-use it have it clearly seprated? Something like "normalizePath"

I have found that upgrading `nette/utils` from 3.2 to 4.0 they have added the method `FileSystem::unixSlashes($path)` which is exactly what we need 😄 
I've already checked that there are not breaking changes with your package if we upgrade `nette/utils` to 4.0.

Do you prefer upgrade or only extraction method??

If only extraction, do you prefer `normalizePath($path)` method on both `PatchDiffer` and `PathResolver` class or I create a new class `FileSystem`, maybe under `Symplify\VendorPatches\Utils` namespace, and put method inside it??

**Comment by TomasVotruba** [comment]
Extraction method is good enough. `FileSystemHelper` with static method is fine with me :+1:

**Comment by BoGnY** [comment]
Done. I've also fixed test so it not fails on Windows machine.

**Comment by TomasVotruba** [comment]
Thank you

**Comment by BoGnY** [comment]
@TomasVotruba can you tag a new release??

**Comment by TomasVotruba** [comment]
Sure, 11.3.0 is out now :+1:

**Pull request merged**
